In [3]:
from sklearn.mixture import GaussianMixture
import torch 
torch.manual_seed(42)
a = torch.randn((1000,768))
gm = GaussianMixture(n_components=10, random_state=42,verbose=2)
b = gm.fit(a)

Initialization 0
Initialization converged. time lapse 3.72448s	 lower bound 3273.00011.


In [4]:
b.bic(a)

13905438.544569485

In [5]:
b.predict(a)

array([1, 7, 1, 9, 1, 9, 3, 3, 5, 5, 8, 6, 9, 1, 5, 3, 9, 9, 4, 3, 1, 9,
       7, 7, 9, 3, 1, 6, 9, 7, 9, 1, 3, 9, 9, 7, 9, 9, 6, 9, 5, 3, 3, 1,
       7, 7, 7, 8, 7, 5, 6, 2, 9, 6, 5, 1, 1, 1, 9, 3, 7, 1, 3, 9, 3, 9,
       9, 7, 1, 5, 9, 6, 3, 1, 3, 9, 1, 1, 9, 5, 9, 9, 9, 5, 9, 9, 9, 7,
       1, 8, 9, 6, 7, 6, 3, 5, 9, 9, 9, 2, 6, 8, 3, 9, 5, 1, 9, 9, 5, 3,
       6, 1, 9, 5, 1, 3, 5, 3, 7, 5, 9, 8, 7, 7, 9, 7, 8, 3, 9, 8, 1, 1,
       3, 9, 9, 7, 7, 7, 9, 9, 1, 2, 9, 7, 1, 7, 9, 3, 6, 1, 1, 5, 8, 6,
       7, 2, 5, 9, 1, 2, 9, 3, 9, 1, 6, 9, 9, 6, 7, 8, 1, 2, 1, 9, 7, 2,
       1, 9, 3, 9, 7, 1, 9, 4, 7, 9, 5, 0, 7, 7, 5, 2, 7, 9, 3, 9, 3, 7,
       5, 9, 7, 9, 8, 3, 5, 1, 9, 1, 7, 3, 6, 2, 5, 5, 9, 9, 9, 1, 9, 1,
       6, 1, 6, 9, 1, 6, 8, 9, 7, 7, 9, 7, 5, 3, 5, 9, 9, 9, 3, 7, 9, 6,
       5, 1, 1, 9, 1, 8, 9, 9, 9, 9, 7, 8, 9, 3, 9, 7, 7, 9, 7, 1, 9, 9,
       8, 9, 5, 1, 1, 9, 7, 1, 9, 9, 3, 5, 9, 1, 2, 1, 6, 7, 1, 7, 7, 7,
       1, 6, 3, 9, 5, 3, 6, 2, 9, 7, 5, 9, 9, 5, 3,

In [13]:
b.predict_proba(a)[3]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [19]:
probs = torch.tensor([
    [0.1, 0.8, 0.05],
    [0.3, 0.6, 0.9],
    [0.05, 0.2, 0.1]])


In [29]:
torch.where(probs[0]>0.5)

(tensor([1]),)

In [32]:
a[[0,1]]

tensor([[ 1.9269,  1.4873,  0.9007,  ..., -1.6034, -0.4298,  0.5762],
        [ 0.3444, -3.1016, -1.4587,  ...,  0.2200,  0.3249,  1.3190]])

In [49]:
torch.where(a == a)[0][600:650]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [53]:
a[:,None][:10][:,None]

tensor([[[[ 1.9269,  1.4873,  0.9007,  ..., -1.6034, -0.4298,  0.5762]]],


        [[[ 0.3444, -3.1016, -1.4587,  ...,  0.2200,  0.3249,  1.3190]]],


        [[[-0.8497, -0.6987, -0.2052,  ..., -0.0298,  1.2715,  1.0849]]],


        ...,


        [[[-0.5971, -1.0348,  0.4210,  ...,  0.1757,  0.2550,  0.8070]]],


        [[[-0.3078,  1.3164,  0.7719,  ..., -0.6264, -1.3772, -1.6635]]],


        [[[-0.4334,  2.2704,  2.0012,  ..., -0.7991,  0.6081, -0.8028]]]])

In [125]:
c = torch.tensor([[3,2,3],[3,2,3],[3,1,3]])
d = torch.tensor([[[3,1,3]],[[3,1,3]]])

In [112]:
(c==d).shape

torch.Size([2, 3, 3])

In [102]:
d.shape

torch.Size([2, 1, 3])

In [109]:
c.shape

torch.Size([3, 3])

In [126]:
torch.where((d==c).all(-1))

(tensor([0, 1]), tensor([2, 2]))

In [127]:
d[0]

tensor([[3, 1, 3]])

In [128]:
import umap

ModuleNotFoundError: No module named 'umap'